{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNgU8K9sX/dpB3kl8OKBZHE",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/lili-hdz/inteligencia_artificial/blob/main/app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "pip install streamlit pandas"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "RnuDQRqE8dJY",
        "outputId": "ffd7315d-0bc9-4659-adbe-b944ef22a522"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting streamlit\n",
            "  Downloading streamlit-1.51.0-py3-none-any.whl.metadata (9.5 kB)\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)\n",
            "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)\n",
            "Requirement already satisfied: cachetools<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.2)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.0)\n",
            "Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)\n",
            "Requirement already satisfied: packaging<26,>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (25.0)\n",
            "Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)\n",
            "Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.5)\n",
            "Requirement already satisfied: pyarrow<22,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)\n",
            "Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.5.0)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)\n",
            "Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)\n",
            "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.45)\n",
            "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
            "  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)\n",
            "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.1)\n",
            "Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.11.0)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.4)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2025.10.5)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.3)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)\n",
            "Downloading streamlit-1.51.0-py3-none-any.whl (10.2 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m10.2/10.2 MB\u001b[0m \u001b[31m69.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.9/6.9 MB\u001b[0m \u001b[31m95.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: pydeck, streamlit\n",
            "Successfully installed pydeck-0.9.1 streamlit-1.51.0\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ILuCndeB8RJR",
        "outputId": "1504c15f-5a53-4f55-b966-3a56e394c5c4"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-11-20 06:28:13.327 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.330 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.542 \n",
            "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
            "  command:\n",
            "\n",
            "    streamlit run /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py [ARGUMENTS]\n",
            "2025-11-20 06:28:13.544 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.545 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.546 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.547 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.549 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.550 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.551 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.552 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.553 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.554 Session state does not function when running a script without `streamlit run`\n",
            "2025-11-20 06:28:13.559 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.561 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.562 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.563 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.564 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.564 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.565 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.566 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.567 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.568 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.569 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.569 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.570 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.572 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.572 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.574 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.578 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.585 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.592 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.596 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.596 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.597 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.604 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.607 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.608 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.609 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.609 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.611 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.611 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.612 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.614 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.616 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.616 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.618 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.618 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.619 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.620 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.620 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.622 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.622 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.623 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.624 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.625 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.626 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.627 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.628 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.630 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.630 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.631 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.632 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.632 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.633 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.634 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.634 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.636 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.636 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.637 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.637 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.638 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.639 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.640 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.641 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.641 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.642 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.643 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.643 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.644 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.645 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.646 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.647 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.647 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.648 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.649 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.650 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.651 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.652 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.653 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.654 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.655 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.656 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.658 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.660 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-20 06:28:13.661 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        }
      ],
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import io\n",
        "\n",
        "# ---------------------------\n",
        "# CONFIGURACIÓN GENERAL\n",
        "# ---------------------------\n",
        "st.set_page_config(\n",
        "    page_title=\"Dame una oportunidad\",\n",
        "    page_icon=\"💼\",\n",
        "    layout=\"wide\"\n",
        ")\n",
        "\n",
        "# Paleta de colores en azul usando CSS sencillo\n",
        "AZUL_FONDO = \"#0f172a\"     # azul oscuro\n",
        "AZUL_PRIMARIO = \"#1d4ed8\"  # azul principal\n",
        "AZUL_CLARO = \"#e0f2fe\"     # azul muy claro\n",
        "BLANCO = \"#ffffff\"\n",
        "\n",
        "st.markdown(\n",
        "    f\"\"\"\n",
        "    <style>\n",
        "        .main {{\n",
        "            background-color: {AZUL_CLARO};\n",
        "        }}\n",
        "        .titulo-principal {{\n",
        "            color: {AZUL_PRIMARIO};\n",
        "            text-align: center;\n",
        "            font-size: 40px;\n",
        "            font-weight: 800;\n",
        "            margin-bottom: 0.5rem;\n",
        "        }}\n",
        "        .subtitulo {{\n",
        "            color: {AZUL_FONDO};\n",
        "            text-align: center;\n",
        "            font-size: 18px;\n",
        "            margin-bottom: 2rem;\n",
        "        }}\n",
        "        .stButton>button {{\n",
        "            background-color: {AZUL_PRIMARIO};\n",
        "            color: {BLANCO};\n",
        "            border-radius: 999px;\n",
        "            padding: 0.5rem 1.5rem;\n",
        "            border: none;\n",
        "        }}\n",
        "        .stButton>button:hover {{\n",
        "            background-color: #1e40af;\n",
        "            color: {BLANCO};\n",
        "        }}\n",
        "    </style>\n",
        "    \"\"\",\n",
        "    unsafe_allow_html=True\n",
        ")\n",
        "\n",
        "st.markdown('<div class=\"titulo-principal\">Dame una oportunidad</div>', unsafe_allow_html=True)\n",
        "st.markdown(\n",
        "    '<div class=\"subtitulo\">Plataforma para gestionar candidatos, manuales y estadísticas</div>',\n",
        "    unsafe_allow_html=True\n",
        ")\n",
        "\n",
        "# ---------------------------\n",
        "# ESTADO INICIAL\n",
        "# ---------------------------\n",
        "if \"df_usuarios\" not in st.session_state:\n",
        "    st.session_state.df_usuarios = pd.DataFrame(\n",
        "        columns=[\"nombre\", \"ocupacion\", \"habilidades\", \"email\", \"telefono\"]\n",
        "    )\n",
        "\n",
        "if \"manual_bytes\" not in st.session_state:\n",
        "    st.session_state.manual_bytes = None\n",
        "    st.session_state.manual_nombre = None\n",
        "    st.session_state.manual_tipo = None\n",
        "\n",
        "# ---------------------------\n",
        "# SIDEBAR: CARGA DE BASE DE DATOS\n",
        "# ---------------------------\n",
        "st.sidebar.title(\"Configuración de datos\")\n",
        "\n",
        "st.sidebar.markdown(\"**1. Cargar base de datos de usuarios (CSV)**\")\n",
        "archivo_csv = st.sidebar.file_uploader(\n",
        "    \"Sube tu archivo CSV de usuarios\",\n",
        "    type=[\"csv\"],\n",
        "    key=\"csv_usuarios\"\n",
        ")\n",
        "\n",
        "if archivo_csv is not None:\n",
        "    try:\n",
        "        df = pd.read_csv(archivo_csv)\n",
        "        # Intentamos asegurar que tenga las columnas mínimas\n",
        "        columnas_necesarias = [\"nombre\", \"ocupacion\", \"habilidades\", \"email\", \"telefono\"]\n",
        "        faltantes = [c for c in columnas_necesarias if c not in df.columns]\n",
        "        if faltantes:\n",
        "            st.sidebar.error(\n",
        "                \"El CSV debe contener al menos estas columnas: \"\n",
        "                + \", \".join(columnas_necesarias)\n",
        "            )\n",
        "        else:\n",
        "            st.session_state.df_usuarios = df[columnas_necesarias]\n",
        "            st.sidebar.success(\"Base de datos cargada correctamente.\")\n",
        "    except Exception as e:\n",
        "        st.sidebar.error(f\"Error al leer el CSV: {e}\")\n",
        "\n",
        "st.sidebar.markdown(\"---\")\n",
        "st.sidebar.markdown(\n",
        "    \"**Nota:** También puedes empezar sin CSV, la base de datos se irá llenando con el formulario.\"\n",
        ")\n",
        "\n",
        "# ---------------------------\n",
        "# SECCIÓN: SUBIR Y DESCARGAR MANUAL\n",
        "# ---------------------------\n",
        "st.markdown(\"### Manual para descargar (subida y descarga)\")\n",
        "\n",
        "col_manual1, col_manual2 = st.columns(2)\n",
        "\n",
        "with col_manual1:\n",
        "    manual_file = st.file_uploader(\n",
        "        \"Sube el manual (PDF, DOCX, etc.)\",\n",
        "        type=None,  # cualquier tipo\n",
        "        key=\"manual\"\n",
        "    )\n",
        "    if manual_file is not None:\n",
        "        st.session_state.manual_bytes = manual_file.read()\n",
        "        st.session_state.manual_nombre = manual_file.name\n",
        "        st.session_state.manual_tipo = manual_file.type or \"application/octet-stream\"\n",
        "        st.success(f\"Manual '{st.session_state.manual_nombre}' cargado correctamente.\")\n",
        "\n",
        "with col_manual2:\n",
        "    if st.session_state.manual_bytes is not None:\n",
        "        st.download_button(\n",
        "            label=f\"Descargar manual: {st.session_state.manual_nombre}\",\n",
        "            data=st.session_state.manual_bytes,\n",
        "            file_name=st.session_state.manual_nombre,\n",
        "            mime=st.session_state.manual_tipo,\n",
        "            key=\"descargar_manual\"\n",
        "        )\n",
        "    else:\n",
        "        st.info(\"Aún no se ha subido ningún manual para descargar.\")\n",
        "\n",
        "st.markdown(\"---\")\n",
        "\n",
        "# ---------------------------\n",
        "# SECCIÓN: TABLA DE USUARIOS\n",
        "# ---------------------------\n",
        "st.markdown(\"### Base de datos de usuarios\")\n",
        "\n",
        "if st.session_state.df_usuarios.empty:\n",
        "    st.info(\"La base de datos aún está vacía. Agrega usuarios desde el formulario inferior.\")\n",
        "else:\n",
        "    st.dataframe(st.session_state.df_usuarios, use_container_width=True)\n",
        "\n",
        "# ---------------------------\n",
        "# SECCIÓN: FORMULARIO PARA AGREGAR USUARIOS\n",
        "# ---------------------------\n",
        "st.markdown(\"### Agregar nuevos usuarios a la base de datos\")\n",
        "\n",
        "with st.form(\"form_nuevo_usuario\"):\n",
        "    col1, col2 = st.columns(2)\n",
        "    with col1:\n",
        "        nombre = st.text_input(\"Nombre completo\")\n",
        "        ocupacion = st.text_input(\"Ocupación (ej. Desarrollador, Diseñador)\")\n",
        "        habilidades = st.text_input(\n",
        "            \"Habilidades (separadas por coma, ej. Python, SQL, Comunicación)\"\n",
        "        )\n",
        "    with col2:\n",
        "        email = st.text_input(\"Correo electrónico\")\n",
        "        telefono = st.text_input(\"Teléfono o medio de contacto\")\n",
        "\n",
        "    enviado = st.form_submit_button(\"Agregar usuario\")\n",
        "\n",
        "    if enviado:\n",
        "        if not nombre or not ocupacion or not email:\n",
        "            st.error(\"Por favor, completa al menos Nombre, Ocupación y Correo electrónico.\")\n",
        "        else:\n",
        "            nuevo = {\n",
        "                \"nombre\": nombre,\n",
        "                \"ocupacion\": ocupacion,\n",
        "                \"habilidades\": habilidades,\n",
        "                \"email\": email,\n",
        "                \"telefono\": telefono,\n",
        "            }\n",
        "            st.session_state.df_usuarios = pd.concat(\n",
        "                [st.session_state.df_usuarios, pd.DataFrame([nuevo])],\n",
        "                ignore_index=True\n",
        "            )\n",
        "            st.success(f\"Usuario '{nombre}' agregado correctamente.\")\n",
        "\n",
        "# ---------------------------\n",
        "# SECCIÓN: ESTADÍSTICAS\n",
        "# ---------------------------\n",
        "st.markdown(\"### Estadísticas de la base de datos de usuarios\")\n",
        "\n",
        "df = st.session_state.df_usuarios\n",
        "\n",
        "if df.empty:\n",
        "    st.info(\"Aún no hay datos para mostrar estadísticas.\")\n",
        "else:\n",
        "    tab_ocupacion, tab_habilidades, tab_candidatos = st.tabs(\n",
        "        [\"Por ocupación\", \"Por habilidades\", \"Elegir candidato\"]\n",
        "    )\n",
        "\n",
        "    # --------- Estadísticas por ocupación ---------\n",
        "    with tab_ocupacion:\n",
        "        st.markdown(\"#### Distribución de usuarios por ocupación\")\n",
        "        ocupaciones = df[\"ocupacion\"].value_counts().reset_index()\n",
        "        ocupaciones.columns = [\"ocupacion\", \"cantidad\"]\n",
        "        st.bar_chart(\n",
        "            ocupaciones.set_index(\"ocupacion\"),\n",
        "            height=350\n",
        "        )\n",
        "        st.dataframe(ocupaciones, use_container_width=True)\n",
        "\n",
        "    # --------- Estadísticas por habilidades ---------\n",
        "    with tab_habilidades:\n",
        "        st.markdown(\"#### Distribución de usuarios por habilidades\")\n",
        "\n",
        "        # Expandir habilidades separadas por comas a filas\n",
        "        def explotar_habilidades(row):\n",
        "            if pd.isna(row[\"habilidades\"]) or str(row[\"habilidades\"]).strip() == \"\":\n",
        "                return []\n",
        "            return [h.strip() for h in str(row[\"habilidades\"]).split(\",\") if h.strip()]\n",
        "\n",
        "        filas = []\n",
        "        for _, row in df.iterrows():\n",
        "            for hab in explotar_habilidades(row):\n",
        "                filas.append({\"habilidad\": hab})\n",
        "\n",
        "        if filas:\n",
        "            df_hab = pd.DataFrame(filas)\n",
        "            habilidades_count = df_hab[\"habilidad\"].value_counts().reset_index()\n",
        "            habilidades_count.columns = [\"habilidad\", \"cantidad\"]\n",
        "            st.bar_chart(\n",
        "                habilidades_count.set_index(\"habilidad\"),\n",
        "                height=350\n",
        "            )\n",
        "            st.dataframe(habilidades_count, use_container_width=True)\n",
        "        else:\n",
        "            st.info(\n",
        "                \"No hay habilidades registradas aún. Agrega habilidades en el formulario de usuarios.\"\n",
        "            )\n",
        "\n",
        "    # --------- Elegir candidato y ver contacto ---------\n",
        "    with tab_candidatos:\n",
        "        st.markdown(\"#### Buscar y seleccionar candidatos\")\n",
        "\n",
        "        col_f1, col_f2 = st.columns(2)\n",
        "        with col_f1:\n",
        "            filtro_ocupacion = st.selectbox(\n",
        "                \"Filtrar por ocupación\",\n",
        "                options=[\"(Todas)\"] + sorted(df[\"ocupacion\"].dropna().unique().tolist())\n",
        "            )\n",
        "        with col_f2:\n",
        "            texto_habilidad = st.text_input(\n",
        "                \"Filtrar por habilidad (ej. Python, Ventas)\",\n",
        "                placeholder=\"Deja vacío para no filtrar por habilidad\"\n",
        "            )\n",
        "\n",
        "        df_filtrado = df.copy()\n",
        "\n",
        "        # Filtro por ocupación\n",
        "        if filtro_ocupacion != \"(Todas)\":\n",
        "            df_filtrado = df_filtrado[df_filtrado[\"ocupacion\"] == filtro_ocupacion]\n",
        "\n",
        "        # Filtro por habilidad (búsqueda simple en el texto de habilidades)\n",
        "        if texto_habilidad.strip():\n",
        "            t = texto_habilidad.strip().lower()\n",
        "            df_filtrado = df_filtrado[\n",
        "                df_filtrado[\"habilidades\"].fillna(\"\").str.lower().str.contains(t)\n",
        "            ]\n",
        "\n",
        "        if df_filtrado.empty:\n",
        "            st.warning(\"No se encontraron candidatos con los filtros seleccionados.\")\n",
        "        else:\n",
        "            candidato_nombres = df_filtrado[\"nombre\"].tolist()\n",
        "            seleccionado = st.selectbox(\n",
        "                \"Elige un candidato\",\n",
        "                options=candidato_nombres,\n",
        "                index=0\n",
        "            )\n",
        "\n",
        "            candidato = df_filtrado[df_filtrado[\"nombre\"] == seleccionado].iloc[0]\n",
        "\n",
        "            st.markdown(\"##### Información del candidato seleccionado\")\n",
        "            st.write(f\"**Nombre:** {candidato['nombre']}\")\n",
        "            st.write(f\"**Ocupación:** {candidato['ocupacion']}\")\n",
        "            st.write(f\"**Habilidades:** {candidato['habilidades']}\")\n",
        "            st.write(f\"**Correo:** {candidato['email']}\")\n",
        "            st.write(f\"**Teléfono / contacto:** {candidato['telefono']}\")\n",
        "\n",
        "            st.info(\n",
        "                \"Puedes utilizar el correo o teléfono mostrados para ponerte en contacto con el candidato.\"\n",
        "            )"
      ]
    }
  ]
}